services:
  api:
    container_name: back-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_TOKEN=192132633:AAH4plz_K6p9bRxV8ul795l_H5wlHgSTTxc
      - WEB_APP_URL=https://quotex-bot-official.com/
    ports:
      - 5000:5000
  web:
    depends_on: [api]
    container_name: front-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
